### ISSUE TITLE
Hello Tutorial Returning Error - "rpc error: code = Unknown desc = unknown query path: unknown request"

### ISSUE THREAD

**Issue by rruenroeng** [ignite/example#8]
Hi there,

WSL2

Installed the latest versions of the CLI/Ignite/all of the things. Tried following the steps called out in the "Express" and "In-Depth" tutorials. Seeing the following:

> Itsame:~/practice/hello$ hellod q hello say-hello bob
> Error: rpc error: code = Unknown desc = unknown query path: unknown request
> Usage:
>   hellod query hello say-hello [name] [flags]
> 
> Flags:
>       --grpc-addr string   the gRPC endpoint to use for this chain
>       --grpc-insecure      allow gRPC over insecure channels, if not TLS the server must use TLS
>       --height int         Use a specific height to query state at (this can error if the node is pruning state)
>   -h, --help               help for say-hello
>       --node string        <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
>   -o, --output string      Output format (text|json) (default "text")
> 
> Global Flags:
>       --chain-id string     The network chain ID (default "hello")
>       --home string         directory for config and data (default "/home/rruenroeng/.hello")
>       --log_format string   The logging format (json|plain) (default "plain")
>       --log_level string    The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
>       --trace               print out full stack trace on errors`

**Comment by julienrbrt** [comment]
Closing because of stale. Please don't hesitate to repost an issue in https://github.com/ignite/cli if you still encounter the problem.
